#pragma once

#include "Global.hpp"

namespace wnd {
    /**
     * @brief Generic key enum.
     */
    enum class Key : uint8
    {
        BackSpace       = 0x08,
        Tab             = 0x09,
        LineFeed        = 0x0A,
        Clear           = 0x0C,
        Return          = 0x0D,
        Pause           = 0x13,
        ScrollLock      = 0x14,
        SysReq          = 0x15,
        Escape          = 0x1B,
        Space           = 0x20,
        SingleQuote	    = 0x27,
        Comma		    = 0x2C,
        Minus		    = 0x2D,
        Dot		        = 0x2E,
        Slash		    = 0x2F,
        Num0		    = 0x30,
        Num1		    = 0x31,
        Num2		    = 0x32,
        Num3		    = 0x33,
        Num4		    = 0x34,
        Num5		    = 0x35,
        Num6		    = 0x36,
        Num7    	    = 0x37,
        Num8	        = 0x38,
        Num9		    = 0x39,
        Semicolon	    = 0x3B,
        Equals		    = 0x3D,
        LeftBracket	    = 0x5B,
        BackSlash	    = 0x5C,
        RightBracket	= 0x5D,
        BackTick	    = 0x60,
        KeyA            = 0x61,
        KeyB            = 0x62,
        KeyC            = 0x63,
        KeyD            = 0x64,
        KeyE            = 0x65,
        KeyF            = 0x66,
        KeyG            = 0x67,
        KeyH            = 0x68,
        KeyI            = 0x69,
        KeyJ            = 0x6A,
        KeyK            = 0x6B,
        KeyL            = 0x6C,
        KeyM            = 0x6D,
        KeyN            = 0x6E,
        KeyO            = 0x6F,
        KeyP            = 0x70,
        KeyQ            = 0x71,
        KeyR            = 0x72,
        KeyS            = 0x73,
        KeyT            = 0x74,
        KeyU            = 0x75,
        KeyV            = 0x76,
        KeyW            = 0x77,
        KeyX            = 0x78,
        KeyY            = 0x79,
        KeyZ            = 0x7A,
        Function1       = 0xBE,
        Function2       = 0xBF,
        Function3       = 0xC0,
        Function4       = 0xC1,
        Function5       = 0xC2,
        Function6       = 0xC3,
        Function7       = 0xC4,
        Function8       = 0xC5,
        Function9       = 0xC6,
        Function10      = 0xC7,
        Function11      = 0xC8,
        Function12      = 0xC9,
        LeftShift       = 0xE1,
        RightShift      = 0xE2,
        LeftControl     = 0xE3,
        RightControl    = 0xE4,
        CapsLock        = 0xE5,
        ShiftLock       = 0xE6,
        Delete		    = 0xFF,
    };
}
